modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Jaronline/CuttingDelight/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://github.com/Jaronline/CuttingDelight"
logoFile="logo.png"
logoBlur=false
credits="${mod_credits}"
authors="${mod_authors}"
description='''${mod_description}'''
# Mod Compatibility
itemIcon = "cuttingdelight:cutting_board"

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="farmersdelight"
    type="required"
    versionRange="${farmers_delight_version_range}"
    ordering="AFTER"
    side="BOTH"
