name: Release Mod
on:
  workflow_dispatch:
    inputs:
      publish-type:
        description: 'Type of release to publish'
        required: true
        default: 'STABLE'
        type: choice
        options:
          - STABLE
          - BETA
          - ALPHA

env:
  PUBLISH_TYPE: ${{ inputs.publish-type }}
  ORG_GRADLE_PROJECT_modrinthToken: ${{ secrets.MODRINTH_TOKEN }}
  ORG_GRADLE_PROJECT_curseforgeApikey: ${{ secrets.CURSEFORGE_API_KEY }}

jobs:
  release:
    name: Release Mod
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Gradle
        uses: Jaronline/.github/actions/setup-java-gradle@main

      - name: Build package
        run: ./gradlew build

      - name: Publish package
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish CurseForge
        run: ./gradlew publishCurseforge

      - name: Publish Modrinth
        run: ./gradlew publishModrinth
